### ISSUE TITLE
fails on react server side rendering

### ISSUE THREAD

**Issue by rishisharma08** [eldargab/load-script#14]
ReferenceError: document is not defined
at load (/node_modules/load-script/index.js:3:28)
...

**Comment by XieX** [comment]
@rishisharma08 It'll only work if it gets executed in the browser. Make sure you're calling load-script from within a `render` method, or some other part of the [component lifecycle](https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle) (e.g. I'm using it in `componentDidMount` successfully).
