### ISSUE TITLE
Type definitions for TypeScript

### ISSUE THREAD

**Issue by dartess** [eldargab/load-script#23]
Hi @eldargab ! How do you feel about TypeScript? There seems to be no types for your package. Would you mind including type definitions in the npm package? I could work on it.

**Comment by eldargab** [comment]
Hi! 

I don't mind at all, but I don't have rights for npm package, so we have to ask @defunctzombie about that.

**Comment by defunctzombie** [comment]
@eldargab What's your npm username?

**Comment by eldargab** [comment]
@defunctzombie , it's `eldar` - https://www.npmjs.com/~eldar

**Comment by defunctzombie** [comment]
@eldargab I've added you as an owner to the package

**Comment by eldargab** [comment]
Ok, so @dartess, I am open to your PR.

**Comment by dartess** [comment]
https://github.com/eldargab/load-script/pull/24

**Comment by eldargab** [comment]
New version with type definitions is now on npm
