### ISSUE TITLE
Add a `cleanup()` mechanism?

### ISSUE THREAD

**Issue by TooTallNate** [eldargab/load-script#7]
It seems to me that if we're using this module to be injecting lots of script tags, then the `<head>` will fill up rather quickly with no way to release the memory of the script tags.

Should we add a cleanup mechanism of some kind?

**Comment by jsdevel** [comment]
@TooTallNate see https://github.com/eldargab/load-script/pull/9.  I believe once that's merged, you could do this:

```javascript
require('load-script', function(err, script) {
  script.parentNode.removeChild(script);
});
```

**Comment by defunctzombie** [comment]
#9 has been merged and released.

Willing to look at a patch that does it automatically if we think that would be better.
